### ISSUE TITLE
error to open an xlsx file

### ISSUE THREAD

**Issue by marceloatmartins** [Ark4ne/xl-reader#6]
Just trying to open an xlsx file using the xl-reader, facing the messages below:
Warning: XMLReader::open(zip://usuario.xlsx#xl/workbook.xml): Failed to open stream: operation failed in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php on line 471

Warning: XMLReader::open(): Unable to open source data in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php on line 471

Fatal error: Uncaught Ark4ne\XlReader\Exception\ReaderException: Can't open part xl/workbook.xml. in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php:472 Stack trace: #0 C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php(435): Ark4ne\XlReader\Reader\XlsxReader->getXMLReader('xl/workbook.xml') #1 C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php(105): Ark4ne\XlReader\Reader\XlsxReader->loadWorkbook() #2 C:\xampp\htdocs\docpronto\loadexcel.php(9): Ark4ne\XlReader\Reader\XlsxReader->load() #3 {main} thrown in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php on line 472

**Comment by marceloatmartins** [comment]
Hi Everyone,
Can you help me with this error, please?
Thanks in advance

**Comment by marceloatmartins** [comment]
The error:

Just trying to open an xlsx file using the xl-reader, facing the messages below:
Warning: XMLReader::open(zip://usuario.xlsx#xl/workbook.xml): Failed to open stream: operation failed in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php on line 471

Warning: XMLReader::open(): Unable to open source data in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php on line 471

Fatal error: Uncaught Ark4ne\XlReader\Exception\ReaderException: Can't open part xl/workbook.xml. in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php:472 Stack trace: #0 C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php(435): Ark4ne\XlReader\Reader\XlsxReader->getXMLReader('xl/workbook.xml') https://github.com/Ark4ne/xl-reader/pull/1 C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php(105): Ark4ne\XlReader\Reader\XlsxReader->loadWorkbook() https://github.com/Ark4ne/xl-reader/pull/2 C:\xampp\htdocs\docpronto\loadexcel.php(9): Ark4ne\XlReader\Reader\XlsxReader->load() https://github.com/Ark4ne/xl-reader/pull/3 {main} thrown in C:\xampp\htdocs\docpronto\vendor\ark4ne\xl-reader\src\Reader\XlsxReader.php on line 472

**Comment by marceloatmartins** [comment]
I've changed to new component.
